server:
  port: 8001
spring:
  application:
    name: provider-ticket
eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
#    instance-id: 127.0.0.1:${server.port}

  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
